name=input("Enter your name: ")
std_id=input("Enter your student ID: ")
std_department=input("Enter your department: ")
github_username=input("Enter your GitHub username: ")
programming_goal=input("Enter one programming goal: ")
#
print(f"---Student Card---")
print(f"Student name: {name}")
print(f"Student ID: {std_id}")
print(f"Student department: {std_department}")
print(f"GitHub username: {github_username}")
print(f"Programming goal: {programming_goal}")
